/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lilianngweta' at '6/8/16 9:43 PM' with Gradle 2.13
 *
 * @author lilianngweta, @date 6/8/16 9:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
